#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_8
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_7
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_1
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_16
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_15
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define BUILTIN_LED_GPIO GPIO_NUM_42

#define DISPLAY_SPI_HOST    SPI3_HOST
#define DISPLAY_SPI_MODE    0
#define DISPLAY_SCLK_PIN    GPIO_NUM_12
#define DISPLAY_MOSI_PIN    GPIO_NUM_11
#define DISPLAY_MISO_PIN    GPIO_NUM_13
#define DISPLAY_CS_PIN      GPIO_NUM_10
#define DISPLAY_DC_PIN      GPIO_NUM_46
#define DISPLAY_RESET_PIN   GPIO_NUM_NC
#define DISPLAY_SPI_SCLK_HZ (40 * 1000 * 1000)

// The panel is physically 240x320. Xiaozhi renders it in landscape mode.
#define DISPLAY_WIDTH        320
#define DISPLAY_HEIGHT       240
#define DISPLAY_SWAP_XY      true
#define DISPLAY_MIRROR_X     false
#define DISPLAY_MIRROR_Y     false
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_RGB_ORDER    LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X     0
#define DISPLAY_OFFSET_Y     0

#define DISPLAY_BACKLIGHT_PIN          GPIO_NUM_45
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define TOUCH_RESET_PIN GPIO_NUM_18
#define TOUCH_INT_PIN   GPIO_NUM_17

#define BATTERY_ADC_UNIT    ADC_UNIT_1
#define BATTERY_ADC_CHANNEL ADC_CHANNEL_8

#define SDCARD_MOUNT_POINT "/sdcard"
#define SDCARD_CLK_PIN GPIO_NUM_38
#define SDCARD_CMD_PIN GPIO_NUM_40
#define SDCARD_D0_PIN  GPIO_NUM_39
#define SDCARD_D1_PIN  GPIO_NUM_41
#define SDCARD_D2_PIN  GPIO_NUM_48
#define SDCARD_D3_PIN  GPIO_NUM_47

#endif  // _BOARD_CONFIG_H_
